
# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  linux-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
#        go-version: ['1.21.x', '1.22.x' ]
        go-version: ['1.21.x' ]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go ${{ matrix.go-version }}
      uses: actions/setup-go@v5
      with:
        go-version: ${{ matrix.go-version }}

    - name: Generate test includes
      run: |
        echo pkgs=$(go list ./... | grep -v /examples/) >> "$GITHUB_ENV"

    - name: Run tests
      run: go test $pkgs -count 100 -coverprofile=./cover.out -covermode=atomic

    - name: Check test coverage
      uses: vladopajic/go-test-coverage@v2
      with:
        config: ./.testcoverage.yml
  
  # windows-tests:
  #   runs-on: windows-latest
  #   strategy:
  #     matrix:
  #       go-version: ['1.21.x', '1.22.x' ]

  #   steps:
  #   - uses: actions/checkout@v4

  #   - name: Set up Go ${{ matrix.go-version }}
  #     uses: actions/setup-go@v5
  #     with:
  #       go-version: ${{ matrix.go-version }}

  #   - name: Test
  #     run: go test ./... -count 100

